services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'voluntariese'
    volumes:
      - database:/var/lib/mysql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  database: