services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: voluntariese
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - database:/var/lib/postgresql/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
    ports:
      - "5173:5173"
    restart: unless-stopped

  api:
    build:
      dockerfile: Dockerfile
      context: "./service"
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./service:/app

volumes:
  database: