/* Replace with your SQL commands *//* Esses comandos sao rodados quando a DB sobe por meio da migration */
/*Eles criam as tables e algumas instancias*/
DROP TABLE IF EXISTS Enrollments;
DROP TABLE IF EXISTS VolunteerServices;
DROP TABLE IF EXISTS Campaigns;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    gender VARCHAR(10) CHECK (gender IN ('male', 'female', 'other')),
    birth_year BIGINT,
    cpf VARCHAR(255) UNIQUE
);

CREATE TABLE Services (
    service_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_name VARCHAR(255),
    service_description VARCHAR(255)
);

CREATE TABLE Campaigns (
    campaign_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    description TEXT,
    creator_id BIGINT,
    requested_service_id BIGINT,
    FOREIGN KEY (creator_id) REFERENCES Users(user_id),
    FOREIGN KEY (requested_service_id) REFERENCES Services(service_id)
);



CREATE TABLE VolunteerServices (
    volunteer_id BIGINT,
    service_id BIGINT,
    FOREIGN KEY (volunteer_id) REFERENCES Users(user_id),
    FOREIGN KEY (service_id) REFERENCES Services(service_id)
);

CREATE TABLE Enrollments (
    campaign_id BIGINT,
    volunteer_id BIGINT,
    FOREIGN KEY (volunteer_id) REFERENCES Users(user_id),
    FOREIGN KEY (campaign_id) REFERENCES Campaigns(campaign_id)
);


-- INSERTIONS
INSERT INTO Users (name, gender, birth_year, cpf) VALUES 
('Alice', 'female', 1990, '12345678901'),
('Bob', 'male', 1985, '23456789012'),
('Charlie', 'female', 1992, '34567890123');

INSERT INTO Services (service_name, service_description) VALUES 
('Tutoring', 'Provide tutoring services for students'),
('Gardening', 'Help with gardening tasks'),
('Cooking', 'Prepare meals for community events');

INSERT INTO Campaigns (name, description, creator_id, requested_service_id) VALUES 
('Back to School', 'Help students with school supplies and tutoring', 1, 1),
('Community Garden', 'Assist in creating and maintaining a community garden', 2, 2);

INSERT INTO VolunteerServices (volunteer_id, service_id) VALUES 
(1, 1),
(2, 2),
(3, 3);

INSERT INTO Enrollments (campaign_id, volunteer_id) VALUES 
(1, 1),
(2, 2);


