/* Replace with your SQL commands */
/* Replace with your SQL commands *//* Esses comandos sao rodados quando a DB sobe por meio da migration */
/*Eles criam as tables e algumas instancias*/
DROP TABLE IF EXISTS Enrollments;
DROP TABLE IF EXISTS VolunteerServices;
DROP TABLE IF EXISTS Campaigns;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
	password VARCHAR(255)NOT NULL,
	profile_description VARCHAR(255),
    gender VARCHAR(10) CHECK (gender IN ('male', 'female', 'other')),
    birth_year BIGINT,
    cpf VARCHAR(255) UNIQUE
);

CREATE TABLE Services (
    service_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_name VARCHAR(255),
    service_description VARCHAR(255)
);

CREATE TABLE Campaigns (
    campaign_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    description TEXT,
    creator_id BIGINT,
    requested_service_id BIGINT,
    FOREIGN KEY (creator_id) REFERENCES Users(user_id),
    FOREIGN KEY (requested_service_id) REFERENCES Services(service_id)
);



CREATE TABLE VolunteerServices (
    volunteer_id BIGINT,
    service_id BIGINT,
    FOREIGN KEY (volunteer_id) REFERENCES Users(user_id),
    FOREIGN KEY (service_id) REFERENCES Services(service_id)
);

CREATE TABLE Enrollments (
    campaign_id BIGINT,
    volunteer_id BIGINT,
    FOREIGN KEY (volunteer_id) REFERENCES Users(user_id),
    FOREIGN KEY (campaign_id) REFERENCES Campaigns(campaign_id)
);


-- INSERTIONS

INSERT INTO Users (name, password, profile_description, gender, birth_year, cpf) VALUES
('Alice Santos', 'password123', 'Loves volunteering and organizing campaigns.', 'female', 1990, '12345678901'),
('Carlos Oliveira', 'securePass456', 'Passionate about community projects.', 'male', 1985, '98765432109'),
('Joana Silva', 'joanaPass789', NULL, 'female', 1995, '12312312345'),
('Rafael Costa', 'rafaelSecure99', 'Expert in organizing tech workshops.', 'male', 1992, '45645645678'),
('Sam Taylor', 'samTheHelper01', 'Non-binary volunteer passionate about inclusivity.', 'other', 1998, '78978978900');


INSERT INTO Services (service_name, service_description) VALUES
('Food Distribution', 'Help distribute food to underprivileged communities.'),
('Tech Workshop', 'Teach basic computer skills to community members.'),
('Cleaning Drive', 'Participate in cleaning up parks and public spaces.'),
('Counseling Support', 'Provide mental health support for youth.');


INSERT INTO Campaigns (name, description, creator_id, requested_service_id) VALUES
('Tech4All Workshop', 'A campaign to teach computer skills to people in need.', 1, 2),
('Healthy Meals for All', 'Distributing healthy meals to those in need.', 2, 1),
('Park Beautification Drive', 'Join us in cleaning and beautifying the local parks.', 3, 3),
('Youth Counseling Initiative', 'Offering free counseling sessions to local youth.', 4, 4);


INSERT INTO VolunteerServices (volunteer_id, service_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 1),
(5, 3);


INSERT INTO Enrollments (campaign_id, volunteer_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 4),
(3, 5),
(4, 5);


